# Generated by Django 3.1.4 on 2020-12-14 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotLogUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=75)),
                ('profile_image_url', models.ImageField(null=True, upload_to='profile_image_url')),
                ('location', models.CharField(max_length=75)),
                ('created_on', models.DateField()),
                ('active', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='0000-00-00')),
                ('make_and_model', models.CharField(max_length=50)),
                ('aircraftId', models.CharField(max_length=25)),
                ('fromAiport', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
                ('landingsDay', models.IntegerField()),
                ('landingsNight', models.IntegerField()),
                ('number_of_instrument_approaches', models.IntegerField()),
                ('type_and_location', models.CharField(max_length=50)),
                ('airplane_single_multi', models.BooleanField(default=True)),
                ('airplane_single_multi_hours', models.IntegerField()),
                ('intrumentActual', models.IntegerField()),
                ('simulator_hood', models.IntegerField()),
                ('ftd_or_simulator', models.IntegerField()),
                ('night', models.IntegerField()),
                ('cross_country_all', models.IntegerField()),
                ('cross_country_fivezero', models.IntegerField()),
                ('pilot_in_command', models.IntegerField()),
                ('solo', models.IntegerField()),
                ('ground_training', models.IntegerField()),
                ('flight_training_received', models.IntegerField()),
                ('flight_training_given', models.IntegerField()),
                ('total_flight_time', models.IntegerField()),
                ('PilotUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotlogapi.pilotlogusers')),
            ],
        ),
        migrations.CreateModel(
            name='InBetween',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=50)),
                ('NewLogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotlogapi.newlog')),
            ],
        ),
    ]
