# Generated by Django 3.1.4 on 2020-12-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlogapi', '0002_auto_20201214_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newlog',
            old_name='fromAiport',
            new_name='fromAirport',
        ),
    ]
