# Generated by Django 3.1.4 on 2020-12-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlogapi', '0003_auto_20201214_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newlog',
            old_name='intrumentActual',
            new_name='instrumentActual',
        ),
    ]
