# Generated by Django 3.1.2 on 2020-12-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlogapi', '0005_auto_20201214_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlog',
            name='remarks',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='newlog',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
